# Generated by Django 4.0 on 2022-05-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpartumdepression', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
